export class Customer {
    customerId: string;
    name: string;
    username: string;
    password: string;
    guardianType: string;
    guardianName: string;
    address: string;
    citizenship: string;
    state: string;
    country: string;
    email: string;
    gender: string;
    maritalStatus: string;
    contactNumber: string;
    dateOfBirth: Date;
    dateOfRegistration: Date;
    accountNumber: number;
    accountType: string;
    bankName: string;
    branchName: string;
    citizenStatus: string;
    initialDepositAmount: number;
    idProoType: string;
    idDocumentNumber: number;
    refAccHolderName: string;
    refAccHolderAccNo: string;
    refAccHolderAddress: string;
}
